#!/usr/bin/env sh
# Generated by Gradle Wrapper
# Monolithic wrapper script
THIS_JAR="$(dirname "$0")"/gradle/wrapper/gradle-wrapper.jar
if [ ! -f "$THIS_JAR" ]; then
  echo "Downloading Gradle wrapper jar..."
  mkdir -p "$(dirname "$0")"/gradle/wrapper
  curl -o "$THIS_JAR" https://services.gradle.org/distributions/gradle-8.4.1-bin.zip
  unzip -p "$THIS_JAR" gradle/wrapper/gradle-wrapper.jar > "$THIS_JAR"
fi
exec java -jar "$THIS_JAR" "$@"
