@echo off
REM Generated by Gradle Wrapper
set THIS_JAR=%~dp0\gradle\wrapper\gradle-wrapper.jar
if not exist "%THIS_JAR%" (
  echo Downloading Gradle wrapper jar...
  powershell -Command "Invoke-WebRequest -Uri https://services.gradle.org/distributions/gradle-8.4.1-bin.zip -OutFile wrapper.zip"
  powershell -Command "Expand-Archive wrapper.zip -DestinationPath ."
)
java -jar "%THIS_JAR%" %*
