name: Build TrimsSMP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trimsmp-jar
          path: build/libs/trimsmp-1.0.0.jar